source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from webapp.views import IndexViews, ArticleCreateView, ArticleView, MyRedirectView, ArticleUpdateView, \
    ArticleDeleteView, ArticleCommentCreateView, CommentUpdateView, CommentDeleteView , ArticleLikeView , CommentLikeView

app_name = 'webapp'

urlpatterns = [
    path('', IndexViews.as_view(), name='index'),
    path('like/<int:pk>/', ArticleLikeView.as_view(), name='like'),
    path('comment_like/<int:pk>/', CommentLikeView.as_view(), name='comment_like'),
    path('article/<int:pk>/', ArticleView.as_view(), name='article_view'),
    path('article/<int:pk>/comment/add/', ArticleCommentCreateView.as_view(), name='article_comment_add'),
    path('articles/add/', ArticleCreateView.as_view(), name='article_add'),
    path('article/<int:pk>/update', ArticleUpdateView.as_view(), name='article_update'),
    path('article/<int:pk>/delete', ArticleDeleteView.as_view(), name='article_delete'),
    path('comment/<int:pk>/update', CommentUpdateView.as_view(), name='comment_update'),
    path('comment/<int:pk>/delete', CommentDeleteView.as_view(), name='comment_delete'),
    path('redirect_view/', MyRedirectView.as_view())
]

source/webapp/forms.py
from django import forms
from django.forms import widgets, ValidationError
from webapp.models import Article, Comment


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content', 'tags']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
            'tags': widgets.CheckboxSelectMultiple,
        }
        error_messages = {
            'content': {
                'required': 'Поле должно быть заполнено'
            }
        }

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) < 5:
            self.add_error('title', ValidationError('Длина зтого поля должна составлять не меенее %(length)d символов!',
                                                    code='too_short', params={'length': 5}))
        return title

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data['title'] == cleaned_data.get('content', ''):
            raise ValidationError('Текст статьи не должен дублировать ее название!')
        return cleaned_data


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

class ArticleDeleteForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title']

    def clean_title(self):
        title = self.cleaned_data['title']
        if self.instance.title != title:
            raise ValidationError('Названия не совпадают')
        return title

class ArticleDeleteForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title']

    def clean_title(self):
        title = self.cleaned_data['title']
        if self.instance.title != title:
            raise ValidationError('Названия не совпадают')
        return title


class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=50, required=False, label='Найти', widget=widgets.TextInput(attrs={'class': "form-control w-25"}))

source/webapp/views/article_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import Q
from django.urls import reverse_lazy
from django.utils.http import urlencode
from webapp.models import Article
from webapp.forms import ArticleForm, SimpleSearchForm, ArticleDeleteForm
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404
from django.http import JsonResponse

from django.views.generic import RedirectView, ListView, DetailView, CreateView, UpdateView, DeleteView, View


# class TestView(View):
#     def get(self, request, *args, **kwargs):
#         response = JsonResponse({'test': 2, 'test2': [1,2,3]})
#         response = JsonResponse({'ok': 'заебись'})
#         response.status_code =200
#         return response

class ArticleLikeView(View):
    def get(self, request, *args, **kwargs):
        user = request.user
        article = get_object_or_404(Article, pk=self.kwargs.get('pk'))
        if user in article.article_like.all():
            article.article_like.remove(user)
            response = JsonResponse({'get_like': article.get_likes_count() , 'type': 'dislike'})
        else:
            article.article_like.add(user)
            response = JsonResponse({'get_like': article.get_likes_count() , 'type':'like'})
        return response

class IndexViews(ListView):
    template_name = 'article/index.html'
    context_object_name = 'articles'
    model = Article
    ordering = ('-created_at',)
    paginate_by = 3
    paginate_orphans = 2

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(Q(title__icontains=self.search_value) | Q(author__icontains=self.search_value))
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
            context['search'] = self.search_value
        return context


class ArticleView(DetailView):
    template_name = 'article/article_view.html'
    model = Article

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        article = self.object
        comments = article.comments.order_by('-created_at')
        context['comments'] = comments
        return context


class MyRedirectView(RedirectView):
    url = 'https://ccbv.co.uk/projects/Django/4.1/django.views.generic.base/RedirectView/'


class ArticleCreateView(LoginRequiredMixin, CreateView):
    template_name = "article/article_create.html"
    model = Article
    form_class = ArticleForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    # def dispatch(self, request, *args, **kwargs):
    #     if not request.user.is_authenticated:
    #         return redirect('accounts:login')
    #     if not request.user.has_perm('webapp.add_article'):
    #         raise PermissionDenied
    #     return super().dispatch( request, *args, **kwargs)



class ArticleUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = "article/article_update.html"
    form_class = ArticleForm
    model = Article
    context_object_name = 'article'
    permission_required = 'webapp.change_article'

    def has_permission(self):
        return super().has_permission() or self.get_object().author == self.request.user

    # def has_permission(self):
    #     project = get_object_or_404(Project, pk=self.kwargs.get('pk'))
    #     return super().has_permission() and self.request.user in project.user.all()


class ArticleDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'article/article_delete.html'
    model = Article
    context_object_name = 'article'
    success_url = reverse_lazy('index')
    form_class = ArticleDeleteForm
    permission_required = 'webapp.delete_article'

    def has_permission(self):
        return super().has_permission() or self.get_object().author == self.request.user

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.form_class(instance=self.object, data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

source/webapp/views/base_views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View, TemplateView


class CreateView(View):
    form_class = None
    template_name = None
    model = None
    redirect_url = None

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        context = {'form': form}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        self.object = form.save()
        return redirect(self.get_redirect_url())

    def form_invalid(self, form):
        context = {'form': form}
        return render(self.request, self.template_name, context)

    def get_redirect_url(self):
        return self.redirect_url


class DeleteView(View):
    template_name = None
    confirm_deletion = True
    model = None
    key_kwarg = 'pk'
    context_key = 'object'
    redirect_url = ''

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.confirm_deletion:
            return render(request, self.template_name, self.get_context_data())
        else:
            self.perform_delete()
            return redirect(self.get_redirect_url())

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.perform_delete()
        return redirect(self.get_redirect_url())

    def perform_delete(self):
        self.object.delete()

    def get_context_data(self, **kwargs):
        return {self.context_key: self.object}

    def get_object(self):
        pk = self.kwargs.get(self.key_kwarg)
        return get_object_or_404(self.model, pk=pk)

    def get_redirect_url(self):
        return self.redirect_url


class UpdateView(View):
    form_class = None
    template_name = None
    redirect_url = ''
    model = None
    key_kwarg = 'pk'
    context_key = 'object'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.form_class(instance=self.object)
        context = self.get_context_data(form=form)
        return render(request, self.template_name, context=context)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.form_class(instance=self.object, data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        self.object = form.save()
        return redirect(self.get_redirect_url())

    def form_invalid(self, form):
        context = self.get_context_data(form=form)
        return render(self.request, self.template_name, context=context)

    def get_object(self):
        pk = self.kwargs.get(self.key_kwarg)
        return get_object_or_404(self.model, pk=pk)

    def get_context_data(self, **my_kwargs):
        context = self.kwargs.copy()
        context[self.context_key] = self.object
        context.update(my_kwargs)
        return context

    def get_redirect_url(self):
        return self.redirect_url


class DetailView(TemplateView):
    context_key = 'object'
    model = None
    key_kwarg = 'pk'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[self.context_key] = self.get_object()
        return context

    def get_object(self):
        pk = self.kwargs.get(self.key_kwarg)
        return get_object_or_404(self.model, pk=pk)


class ListView(TemplateView):
    model = None
    context_key = 'objects'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[self.context_key] = self.get_objects()
        return context

    def get_objects(self):
        return self.model.objects.all()


class FormView(View):
    template_name = None
    form_class = None
    redirect_url = ''

    def get_context_data(self, **kwargs):
        return kwargs

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        context = self.get_context_data(form=form)
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_redirect_url(self):
        return self.redirect_url

    def form_valid(self, form):
        return redirect(self.get_redirect_url())

    def form_invalid(self, form):
        context = self.get_context_data(form=form)
        return render(self.request, self.template_name, context)

source/webapp/views/comment_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, DeleteView , View

from webapp.forms import CommentForm
from webapp.models import Comment, Article
from django.http import JsonResponse

class CommentLikeView(View):
    def get(self, request, *args, **kwargs):
        user = request.user
        comment = get_object_or_404(Comment, pk=self.kwargs.get('pk'))
        print(comment)
        if user in comment.comment_like.all():
            comment.comment_like.remove(user)
            response = JsonResponse({'like': comment.get_comment_likes_count() , 'typec': 'dislike'})
        else:
            comment.comment_like.add(user)
            response = JsonResponse({'like': comment.get_comment_likes_count() , 'typec':'like'})
        return response


class ArticleCommentCreateView(LoginRequiredMixin, CreateView):
    template_name = 'comment/create.html'
    model = Comment
    form_class = CommentForm

    def get_success_url(self):
        return reverse('webapp:article_view', kwargs={'pk': self.object.article.pk})

    def form_valid(self, form):
        article = get_object_or_404(Article, pk=self.kwargs.get('pk'))
        form.instance.article = article
        form.instance.author = self.request.user
        return super().form_valid(form)


class CommentUpdateView(PermissionRequiredMixin, UpdateView):
    model = Comment
    template_name = 'comment/update.html'
    form_class = CommentForm
    context_object_name = 'comment'
    # permission_required = 'webapp.change_comment'

    def has_permission(self):
        return self.request.user.has_perm('webapp.change_comment') or self.get_object().author == self.request.user

    def get_success_url(self):
        return reverse('webapp:article_view', kwargs={'pk': self.object.article.pk})

class CommentDeleteView(UserPassesTestMixin, DeleteView):
    model = Comment

    def test_func(self):
        return self.request.user.has_perm('webapp.delete_comment') or self.get_object().author == self.request.user

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('webapp:article_view', kwargs={'pk': self.object.article.pk })

source/webapp/templates/partial/article_list_partial.html
{% load static %}
    <h1>Articles</h1>
    <div class="row">
        {% for article in articles %}
            <div class="col-4 my-3">
                <div class="card">
                    <div class="card-body" >
                        <h5 class="card-title">Заголовок: {{ article.title }} ({{ article.get_comments_count }})</h5>
                        <p class="card-text">Автор: {{ article.author }}</p>
                        <p class="card-text">Теги: {% for tag in article.tags.all %}
                            {{ tag.name }} {% if  not forloop.last %},{% endif %}
                        {% endfor %}</p>
                        <a href="{{ article.get_absolute_url }}" class="btn btn-primary">Подробнее...</a>
                    <div class="mt-2 d-flex">
                    {% if request.user.is_authenticated %}
                        <button class="btn btn-success" data-pk="{{ article.pk }}" onclick="buttonClick(event)" id="button_{{ article.pk }}" data-link="{% url 'webapp:like' article.pk %}">
                        {% if request.user in article.article_like.all %}Dislike{% endif %}
                        {% if request.user not in article.article_like.all %}Like{% endif %}
                        </button>
                    {% endif %}
                        <p class="ms-1" id="count_{{ article.pk }}">Likes {{ article.get_likes_count }}</p>
                    </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}

    <script src="{% static 'js/main.js' %}"></script>

source/webapp/templates/partial/form.html
{% if not fields_only %}
{% csrf_token %}
{% endif %}

{% for error in form.non_field_errors %}
    <p class="text-danger">{{ error }}</p>
{% endfor %}

{% for field in form %}
    <div class="form-check">
        <p><label for="{{ field.id_for_label }}">{{ field.label }}</label></p>
        <p class="w-50">{{ field }}</p>
        {% for error in field.errors %}
            <p class="text-danger">{{ error }}</p>
        {% endfor %}
    </div>
{% endfor %}


{% if not fields_only %}
<div class="form-check">
    <input type="submit" class="btn btn-primary px-5" value="{{ button_text }}"/>
</div>
{% endif %}

source/webapp/templates/partial/pagination.html
<div class="d-flex justify-content-center">
    <ul class="pagination">
        {% if not page_obj.has_previous %}
            <li class="page-item disabled">
                <a class="page-link">&laquo; В начало</a>
            </li>
            <li class="page-item disabled">
                <a class="page-link">Назад</a>
            </li>
        {% else %}
            <li class="page-item">
                <a class="page-link" href="?{% if query %}{{ query }}&{% endif %}page=1">&laquo; В начало</a>
            </li>
            <li class="page-item">
                <a class="page-link"
                   href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.previous_page_number }}">Назад</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.previous_page_number }}">
                    {{ page_obj.previous_page_number }}
                </a>
            </li>
        {% endif %}

        <li class="page-item active" aria-current="page">
            <form method="get">
                {% if search %}<input type="hidden" name="search" value="{{ search }}">{% endif %}
                <input type="text" class="form-control" name="page" value="{{ page_obj.number }}">
            </form>
            {#        <a class="page-link" href="#">{{ page_obj.number }}</a>#}
        </li>

        {% if not page_obj.has_next %}
            <li class="page-item disabled">
                <a class="page-link">Далее</a>
            </li>

            <li class="page-item disabled">
                <a class="page-link">В конец &raquo;</a>

            </li>
        {% else %}
            <li class="page-item">
                <a class="page-link" href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.next_page_number }}">
                    {{ page_obj.next_page_number }}
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.next_page_number }}">Далее</a>
            </li>
            <li class="page-item">
                <a class="page-link"
                   href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.paginator.num_pages }}">В конец
                    &raquo;</a>

            </li>
        {% endif %}
    </ul>
</div>

source/webapp/templates/partial/simple_search.html
<form action="" method="GET">
    <div class="d-flex justify-content-center">
        {{ form.search }}
        <input type="submit" class="btn btn-success ms-1" value="Поиск">
    </div>
    {% for error in form.search.errors %}
        <p class="text-danger">{{ error }}</p>
    {% endfor %}
</form>